name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: NPM Install
        run: npm install

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Docker Scout Scan
        run: |
          docker-scout quickview fs://.
          docker-scout cves fs://.

      - name: Docker Build and Push
        run: |
          docker build -t sholly333/boutique-store:latest .
          docker push sholly333/boutique-store:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Docker Scout Image Scan
        run: |
          docker-scout quickview sholly333/boutique-store:latest
          docker-scout cves sholly333/boutique-store:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Docker Pull Image
        run: docker pull sholly333/boutique-store:latest

      - name: Deploy to Container
        run: docker run -d --name game-new -p 3000:3000 sholly333/boutique-store:latest

      - name: Update Kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: List Files
        run: ls -al  # Check for deployment-service.yml

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml

      - name: Deploy to kubernetes
        run: kubectl delete -f deployment-service.yml
